import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/globals.css'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'
import Header from '@/components/header/header'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode
	params: Promise<{ locale: string }>
}>) {
	const { locale } = await params
	if (!routing.locales.includes((locale as 'en') || 'ka')) {
		notFound()
	}
	const messages = await getMessages()
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable} relative antialiased`}>
				<NextIntlClientProvider messages={messages}>
					<Header />
					<div className='ml-auto mr-auto flex justify-center'>{children}</div>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
