import type { Metadata } from 'next'
import '@/globals.css'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { getMessages } from 'next-intl/server'
import { NextIntlClientProvider } from 'next-intl'
import Header from '@/components/header/header'
import { Cinzel } from 'next/font/google'

const cinzel = Cinzel({
	subsets: ['latin'],
	weight: ['400', '700'], // you can also add '600', etc.
	variable: '--font-cinzel',
})
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode
	params: Promise<{ locale: string }>
}>) {
	const { locale } = await params
	if (!routing.locales.includes((locale as 'en') || 'ka')) {
		notFound()
	}
	const messages = await getMessages()
	return (
		<html lang='en' className={cinzel.variable}>
			<body className={`relative antialiased`}>
				<NextIntlClientProvider messages={messages}>
					<Header />
					<div className='ml-auto mr-auto flex justify-center' aria-label='v1.0'>
						{children}
					</div>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
